services:
  example:
    env_file: &env_file .env
    image: &python_image python:3.12-slim-bookworm
    working_dir: &working_dir /opt/project
    command:
      - poetry
      - run
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes: &volumes
      - site_packages:/usr/local/lib/python3.12/site-packages
      - usr_local_bin:/usr/local/bin
      - poetry_cache:/root/.cache/pypoetry
      - ./src:/opt/project
      - media:/opt/project/media
    depends_on: &depends_on
      - postgres
      - redis
  celery:
    env_file: *env_file
    image: *python_image
    working_dir: *working_dir
    command:
      - poetry
      - run
      - celery
      - --app=example
      - worker
      - --task-events
      - --concurrency=1
      - --loglevel=DEBUG
    volumes: *volumes
    depends_on: *depends_on
  postgres:
    env_file: *env_file
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine

volumes:
  site_packages:
  usr_local_bin:
  poetry_cache:
  pg_data:
  media:
