services:
  example:
    env_file: &env_file .env
    image: python:3.12-slim-bookworm
    working_dir: /opt/project
    command:
      - poetry
      - run
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - site_packages:/usr/local/lib/python3.12/site-packages
      - usr_local_bin:/usr/local/bin
      - poetry_cache:/root/.cache/pypoetry
      - ./src:/opt/project
    depends_on:
      - postgres
  postgres:
    env_file: *env_file
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  site_packages:
  usr_local_bin:
  poetry_cache:
  pg_data:
